export const CATEGORY_COLORS: Record<string, string> = {
  'PSA / Ticketing': 'hsl(221, 83%, 53%)',
  'RMM': 'hsl(262, 83%, 58%)',
  'Documentation': 'hsl(142, 71%, 45%)',
  'Accounting': 'hsl(38, 92%, 50%)',
  'Cybersecurity': 'hsl(0, 84%, 60%)',
  'Backup & DR': 'hsl(199, 89%, 48%)',
  'Networking': 'hsl(172, 66%, 50%)',
  'GRC / Compliance': 'hsl(291, 47%, 51%)',
  'HR': 'hsl(330, 81%, 60%)',
  'Email & Collaboration': 'hsl(213, 94%, 68%)',
  'Identity & Access': 'hsl(43, 96%, 56%)',
  'Sales & CRM': 'hsl(160, 84%, 39%)',
  'Communication': 'hsl(258, 90%, 66%)',
  'Endpoint Management': 'hsl(210, 34%, 63%)',
  'Monitoring': 'hsl(187, 72%, 45%)',
  'vCIO / Lifecycle Management': 'hsl(270, 60%, 55%)',
  'Cloud Platforms': 'hsl(205, 78%, 52%)',
  'Distributors': 'hsl(25, 75%, 55%)',
  'Security Testing': 'hsl(350, 70%, 50%)',
  'Security Awareness Training': 'hsl(45, 85%, 50%)',
  'Email Security': 'hsl(15, 80%, 55%)',
  'Client Portal': 'hsl(195, 65%, 50%)',
  'AI & LLMs': 'hsl(280, 75%, 60%)',
  'Social Media': 'hsl(340, 70%, 55%)',
  'Billing & Invoicing': 'hsl(55, 80%, 48%)',
  'Background Check': 'hsl(120, 45%, 50%)',
  'M365 Management': 'hsl(215, 80%, 50%)',
  'DNS Filtering': 'hsl(185, 75%, 45%)',
  'Virtualization': 'hsl(240, 55%, 55%)',
  'Alerting & Incident Management': 'hsl(10, 78%, 54%)',
  'Automation & Workflow': 'hsl(80, 70%, 48%)',
};

export const CATEGORY_ICONS: Record<string, string> = {
  'PSA / Ticketing': 'Ticket',
  'RMM': 'Monitor',
  'Documentation': 'FileText',
  'Accounting': 'Calculator',
  'Cybersecurity': 'Shield',
  'Backup & DR': 'HardDrive',
  'Networking': 'Network',
  'GRC / Compliance': 'ClipboardCheck',
  'HR': 'Users',
  'Email & Collaboration': 'Mail',
  'Identity & Access': 'Key',
  'Sales & CRM': 'TrendingUp',
  'Communication': 'MessageSquare',
  'Endpoint Management': 'Laptop',
  'Monitoring': 'Activity',
  'vCIO / Lifecycle Management': 'LineChart',
  'Cloud Platforms': 'Cloud',
  'Distributors': 'Package',
  'Security Testing': 'Bug',
  'Security Awareness Training': 'GraduationCap',
  'Email Security': 'ShieldCheck',
  'Client Portal': 'Layout',
  'AI & LLMs': 'Brain',
  'Social Media': 'Share2',
  'Billing & Invoicing': 'Receipt',
  'Background Check': 'UserCheck',
  'M365 Management': 'Settings2',
  'DNS Filtering': 'Filter',
  'Virtualization': 'Server',
  'Alerting & Incident Management': 'Bell',
  'Automation & Workflow': 'Workflow',
};
